---
- hosts: ubuntu@192.168.64.10
  tasks:
    - name: sleep random
      shell: sleep $[ $RANDOM % 3 ]
      args:
        unless: /bin/true
      notify: nginx, systemd
  handlers:
    - name: nginx
      command: echo restarting nginx
