---
- hosts:
    - ubuntu@192.168.64.16
  remote_user: root
  gather_facts: false

  tasks:
    - name: install ssh keys
      command:
        user: ubuntu
        key: "{{item}}"
      loop:
        - abc
        - xyz
