---
- hosts:
    - ubuntu@192.168.64.16
    - ubuntu@192.168.64.17
  remote_user: root
  gather_facts: false

  tasks:
    - name: install ssh keys
      authorized_key:
        user: ubuntu
        key: "{{item}}"
      loop:
        - abc
        - xyz
