---
- hosts:
    - root@192.168.64.19
  tasks:
    - name: file sync
      tree:
        src: fixture/tree
        dst: /tmp
        #        /etc/nginx: handler=nginx
        /: umask=022 handler=sync
  handlers:
    - name: nginx
      command: echo restarting nginx
    - name: apt
      command: echo restarting apt
